project:
  type: website

website:
  title: "plotthedata"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/11rchitwood
      - icon: linkedin
        href: https://linkedin.com/in/11rchitwood/
      - icon: twitter
        href: https://twitter.com/11rchitwood
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

