project:
  type: website

website:
  title: "Plot the Data"
  description: "My Data Science Portfolio"
  site-url: https://plotthedata.com
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/11rchitwood
      - icon: linkedin
        href: https://linkedin.com/in/11rchitwood/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual
